### ISSUE TITLE
Embeds/transclusions

### ISSUE THREAD

**Issue by DutchPete** [mnaoumov/obsidian-better-markdown-links#3]
With the plug-in enabled, this is the syntax I get when I want to transclude a block into another note:

`[2024-07-15, Mon, wk29](<./2024-07-15, Mon, wk29.md#^7upkr6>)`

but when I subsequently hover over that link, the original text does not show up in the pop-up. Of course it does show up in the pop-up with the original embed syntax:

`[2024-07-15, Mon, wk29](2024-07-15,%20Mon,%20wk29.md#^7upkr6)`.

Am I doing something wrong?

**Comment by mnaoumov** [comment]
Works for me

![image](https://github.com/user-attachments/assets/76bc7270-745b-49f8-a612-df3fc59c2273)

Please attach your sample vault to reproduce the issue

**Comment by DutchPete** [comment]
As per #2.

**Comment by DutchPete** [comment]
What is the meaning of `../` in this block link — 2 dots before the slash instead of 1 dot:

`[embrace the blows so you can learn from them](<../Daily-notes-2024/2024-07-15, Mon, wk29.md#^8crwae>)`

**Comment by mnaoumov** [comment]
@DutchPete `../` means the standard thing in the file system: `go to the parent directory`

**Comment by DutchPete** [comment]
So, why are some prepended with a single dot and some with a double dot?

**Comment by mnaoumov** [comment]
Imagine you have three notes: `dir1/note1.md`, `dir1/note2.md`, `dir2/note3.md`

And you insert links/transclusions into `dir1/note1.md`

```md
[note2](<./note2.md>)
[note3](<../dir2/note3.md>)
```

Here we have single dot before `note2.md`, because `note1.md` and `note2.md` belong to the same directory `dir1`.

But we have double dot before `note3.md`, because `note1.md` and `note3.md` don't belong to the same directory, so we need to go to the parent directory, then to `dir2` directory to reach `note3.md`.

That's how `relative path` work. It is not any specific to my plugin or to Obsidian, that's the common thing in file systems

**Comment by DutchPete** [comment]
OK, thanks very much for that explanation.
